DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS books;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  access_token BLOB,
  folder TEXT
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER,
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    pathname TEXT NOT NULL
);