"""empty message

Revision ID: 132961348a39
Revises: 745bdc0f06c
Create Date: 2015-01-24 22:05:49.411810

"""

# revision identifiers, used by Alembic.
revision = '132961348a39'
down_revision = '745bdc0f06c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uploaded_welcome_pdf', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uploaded_welcome_pdf')
    ### end Alembic commands ###
