"""empty message

Revision ID: 16253857f207
Revises: 5a875dac2ed3
Create Date: 2014-12-30 18:22:32.856272

"""

# revision identifiers, used by Alembic.
revision = '16253857f207'
down_revision = '5a875dac2ed3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('added_bookmarklet', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'added_bookmarklet')
    ### end Alembic commands ###
