"""empty message

Revision ID: 18178950b919
Revises: None
Create Date: 2014-07-31 20:21:11.748024

"""

# revision identifiers, used by Alembic.
revision = '18178950b919'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dropbox_id', sa.Integer(), nullable=True),
    sa.Column('kindle_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('emailer', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('emailer'),
    sa.UniqueConstraint('kindle_name')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_hash', sa.Integer(), nullable=True),
    sa.Column('pathname', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('user')
    ### end Alembic commands ###
