"""empty message

Revision ID: 1e87e395a664
Revises: 132961348a39
Create Date: 2015-02-20 02:41:22.318863

"""

# revision identifiers, used by Alembic.
revision = '1e87e395a664'
down_revision = '132961348a39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('unsent', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'unsent')
    ### end Alembic commands ###
