"""empty message

Revision ID: 513e4358097a
Revises: 49fb024e38
Create Date: 2016-07-26 20:17:31.949123

"""

# revision identifiers, used by Alembic.
revision = '513e4358097a'
down_revision = '49fb024e38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('date_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'date_created')
    ### end Alembic commands ###
