"""empty message

Revision ID: 5a875dac2ed3
Revises: 2b46478eeb50
Create Date: 2014-09-09 18:33:25.961143

"""

# revision identifiers, used by Alembic.
revision = '5a875dac2ed3'
down_revision = '2b46478eeb50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
