"""empty message

Revision ID: 745bdc0f06c
Revises: 16253857f207
Create Date: 2015-01-05 22:54:48.240133

"""

# revision identifiers, used by Alembic.
revision = '745bdc0f06c'
down_revision = '16253857f207'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kindle_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindle_name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'user', 'kindle_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('kindle_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_table('kindle_name')
    ### end Alembic commands ###
