"""empty message

Revision ID: d7fc2abf989
Revises: 38715ca1f509
Create Date: 2014-08-02 02:58:22.412667

"""

# revision identifiers, used by Alembic.
revision = 'd7fc2abf989'
down_revision = '38715ca1f509'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    ### end Alembic commands ###
